### ISSUE TITLE
Dialog box should not be cancelled

### ISSUE THREAD

**Issue by rajat-smpx** [rajatgoyal715/Puzzle15#26]
After game completion dialog box can be cancelled, which allows user to continue the game

**Comment by therealshabi** [comment]
Are you taking this issue?

**Comment by rajat-smpx** [comment]
@therealshabi You can take this issue. Assign yourself and branch out from `master`.

**Comment by therealshabi** [comment]
Can you be more specific with the issue please, I mean which dialog box, when does it come, what is the intended behaviour, why is that etc.?

**Comment by rajatgoyal715** [comment]
After the user completes the game, there appears a dialog showing `Do you want to play a new game or not?`. But the issue is that this dialog can be canceled right now, which just allows the user to further move tiles. So, basically, this should be handled as in the dialog box should be made non-cancellable.
